# 作業 : (Kaggle)鐵達尼生存預測
***
- 分數以網站評分結果為準, 請同學實際將提交檔(*.csv)上傳試試看  
https://www.kaggle.com/c/titanic/submit

# [作業目標]
- 試著模仿範例寫法, 在鐵達尼生存預測中, 觀察觀查混合泛化 (Blending) 的寫法與效果

# [作業重點]
- 觀察混合泛化的準確度 (In[14]), 是否比單一模型準確度為高 (In[11~13])  
- 除了我們的權重, 同學也可以試著自行調整權重 (注意:權重和=1), 看看有什麼影響
- Hint : 除了權重, 分類預測的調整, 還可以調整什麼地方?

In [1]:
# 做完特徵工程前的所有準備 (與前範例相同)
import pandas as pd
import numpy as np
import copy, time
import warnings
warnings.filterwarnings('ignore')
from IPython.display import display
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder

data_path = 'data/'
df_train = pd.read_csv(data_path + 'titanic_train.csv')
df_test = pd.read_csv(data_path + 'titanic_test.csv')

train_Y = df_train['Survived']
ids = df_test['PassengerId']
df_train = df_train.drop(['PassengerId', 'Survived'] , axis=1)
df_test = df_test.drop(['PassengerId'] , axis=1)
df = pd.concat([df_train,df_test])
df.head()

,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1309 entries, 0 to 417
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Pclass    1309 non-null   int64
 1   Name      1309 non-null   object
 2   Sex       1309 non-null   object
 3   Age       1046 non-null   float64
 4   SibSp     1309 non-null   int64
 5   Parch     1309 non-null   int64
 6   Ticket    1309 non-null   object
 7   Fare      1308 non-null   float64
 8   Cabin     295 non-null    object
 9   Embarked  1307 non-null   object
dtypes: float64(2), int64(3), object(5)
memory usage: 112.5+ KB

In [2]:
# 檢查 DataFrame 空缺值的狀態
def na_check(df_data):
    data_na = (df_data.isnull().sum() / len(df_data)) * 100
    data_na = data_na.drop(data_na[data_na == 0].index).sort_values(ascending=False)
    missing_data = pd.DataFrame({'Missing Ratio' :data_na})
    display(missing_data.head(10))
na_check(df)

          Missing Ratio
Cabin         77.463713
Age           20.091673
Embarked       0.152788
Fare           0.076394

In [4]:
# 以下 In[3]~In[10] 只是鐵達尼預測中的一組特徵工程, 並以此組特徵工程跑參數, 若更換其他特徵工程, In[10]的參數需要重新跑
# Sex : 直接轉男 0 女 1
df["Sex"] = df["Sex"].map({"male": 0, "female":1})
# Fare : 用 log 去偏態, 0 則直接取 0
df["Fare"] = df["Fare"].map(lambda i: np.log(i) if i > 0 else 0)
# Age : 缺值用中位數補
df["Age"] = df["Age"].fillna(df['Age'].median())

In [6]:
# Title 的 特徵工程 : 將各種頭銜按照類型分類, 最後取 One Hot
df_title = [i.split(",")[1].split(".")[0].strip() for i in df["Name"]]
df["Title"] = pd.Series(df_title)
df["Title"] = df["Title"].replace(['Lady', 'the Countess','Countess','Capt', 'Col','Don', 'Dr', 'Major', 'Rev', 'Sir', 'Jonkheer', 'Dona'], 'Rare')
df["Title"] = df["Title"].map({"Master":0, "Miss":1, "Ms" : 1 , "Mme":1, "Mlle":1, "Mrs":1, "Mr":2, "Rare":3})
df["Title"] = df["Title"].astype(int)
df = pd.get_dummies(df, columns = ["Title"])

In [7]:
# 新建:家庭大小 (Fsize)特徵, 並依照大小分別建獨立欄位
df["Fsize"] = df["SibSp"] + df["Parch"] + 1
df['Single'] = df['Fsize'].map(lambda s: 1 if s == 1 else 0)
df['SmallF'] = df['Fsize'].map(lambda s: 1 if  s == 2  else 0)
df['MedF'] = df['Fsize'].map(lambda s: 1 if 3 <= s <= 4 else 0)
df['LargeF'] = df['Fsize'].map(lambda s: 1 if s >= 5 else 0)

In [8]:
# Ticket : 如果不只是數字-取第一個空白之前的字串(去除'.'與'/'), 如果只是數字-設為'X', 最後再取 One Hot
Ticket = []
for i in list(df.Ticket):
    if not i.isdigit() :
        Ticket.append(i.replace(".","").replace("/","").strip().split(' ')[0])
    else:
        Ticket.append("X")        
df["Ticket"] = Ticket
df = pd.get_dummies(df, columns = ["Ticket"], prefix="T")

In [9]:
# Cabib 依照第一碼分類, 再取 One Hot
df["Cabin"] = pd.Series([i[0] if not pd.isnull(i) else 'X' for i in df['Cabin'] ])
df = pd.get_dummies(df, columns = ["Cabin"], prefix="Cabin")

In [10]:
# Embarked, Pclass 取 One Hot
df = pd.get_dummies(df, columns = ["Embarked"], prefix="Em")
df["Pclass"] = df["Pclass"].astype("category")
df = pd.get_dummies(df, columns = ["Pclass"], prefix="Pc")

# 捨棄 Name 欄位
df.drop(labels = ["Name"], axis = 1, inplace = True)

In [11]:
# 確認缺值 與 目前的資料表內容
na_check(df)
df.head()

Empty DataFrame
Columns: [Missing Ratio]
Index: []

,Sex,Age,SibSp,Parch,Fare,Title_0,Title_1,Title_2,Title_3,Fsize,...,Cabin_F,Cabin_G,Cabin_T,Cabin_X,Em_C,Em_Q,Em_S,Pc_1,Pc_2,Pc_3
0,0,22.0,1,0,1.981001,0,0,1,0,2,...,0,0,0,1,0,0,1,0,0,1
1,1,38.0,1,0,4.266662,0,1,0,0,2,...,0,0,0,0,1,0,0,1,0,0
2,1,26.0,0,0,2.070022,0,1,0,0,1,...,0,0,0,1,0,0,1,0,0,1
3,1,35.0,1,0,3.972177,0,1,0,0,2,...,0,0,0,0,0,0,1,1,0,0
4,0,35.0,0,0,2.085672,0,0,1,0,1,...,0,0,0,1,0,0,1,0,0,1

In [12]:
# 將資料最大最小化
df = MinMaxScaler().fit_transform(df)

# 將前述轉換完畢資料 df , 重新切成 train_X, test_X
train_num = train_Y.shape[0]
train_X = df[:train_num]
test_X = df[train_num:]

# 使用三種模型 : 邏輯斯迴歸 / 梯度提升機 / 隨機森林, 參數使用 Random Search 尋找
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
lr = LogisticRegression(tol=0.001, penalty='l2', fit_intercept=True, C=1.0)
gdbt = GradientBoostingClassifier(tol=100, subsample=0.75, n_estimators=250, max_features=20,
                                  max_depth=6, learning_rate=0.03)
rf = RandomForestClassifier(n_estimators=100, min_samples_split=2, min_samples_leaf=1, 
                            max_features='sqrt', max_depth=6, bootstrap=True)

In [13]:
# 線性迴歸預測檔 (結果有部分隨機, 請以 Kaggle 計算的得分為準, 以下模型同理)
lr.fit(train_X, train_Y)
lr_pred = lr.predict_proba(test_X)[:,1]
sub = pd.DataFrame({'PassengerId': ids, 'Survived': lr_pred})
sub['Survived'] = sub['Survived'].map(lambda x:1 if x>0.5 else 0) 
sub.to_csv('titanic_lr.csv', index=False)

In [15]:
# 梯度提升機預測檔 
gdbt.fit(train_X, train_Y)
gdbt_pred = gdbt.predict_proba(test_X)[:,1]
sub = pd.DataFrame({'PassengerId': ids, 'Survived': gdbt_pred})
sub['Survived'] = sub['Survived'].map(lambda x:1 if x>0.5 else 0) 
sub.to_csv('titanic_gdbt.csv', index=False)

In [16]:
# 隨機森林預測檔
rf.fit(train_X, train_Y)
rf_pred = rf.predict_proba(test_X)[:,1]
sub = pd.DataFrame({'PassengerId': ids, 'Survived': rf_pred})
sub['Survived'] = sub['Survived'].map(lambda x:1 if x>0.5 else 0) 
sub.to_csv('titanic_rf.csv', index=False)

# 作業
* 雖然同樣是混合泛化，分類預測其實與回歸預測有相當多的差異性，
因為鐵達尼預測的結果是 '生存/死亡'，輸出不是 0 就是 1  
因此要用權重混合時，需要以以機率的形式混合，因此我們在作業前幾格當中，先幫各位同學把預測值寫成了機率的形式  
(請同學把下列程式完成，並將結果提交到 Kaggle 網站看看結果)

* 但是光是這樣，分類問題的混合泛化就能比單模預測還要好嗎?  
已經快要期中考了，這裡請同學挑戰看看，還有沒有什麼方法可以改進混合泛化的結果?

In [20]:
# 混合泛化預測檔 
"""
Your Code Here
"""
blending_pred = lr_pred*0.15  + gdbt_pred*0.60 + rf_pred*0.25
sub = pd.DataFrame({'PassengerId': ids, 'Survived': blending_pred})
sub['Survived'] = sub['Survived'].map(lambda x:1 if x>0.6 else 0) 
sub.to_csv('titanic_blending.csv', index=False)

In [18]:
rf_pred

array([0.11685677, 0.59408937, 0.51457109, 0.50382534, 0.29749804,
       0.12612671, 0.45370165, 0.63996329, 0.67284908, 0.48188316,
       0.45420304, 0.63020087, 0.47641465, 0.13993758, 0.87166097,
       0.87393213, 0.44150258, 0.1432947 , 0.51477263, 0.6154921 ,
       0.25528457, 0.34862822, 0.85837152, 0.36692873, 0.81247799,
       0.41836816, 0.50782818, 0.26281541, 0.60439405, 0.16855024,
       0.29460445, 0.75897599, 0.63373927, 0.23378432, 0.32491454,
       0.14794261, 0.26748672, 0.26500077, 0.4229335 , 0.49720417,
       0.49868117, 0.60161651, 0.11658505, 0.78550428, 0.88755491,
       0.14452701, 0.22051077, 0.50273471, 0.48844553, 0.59922224,
       0.61168767, 0.16711848, 0.88410465, 0.69735797, 0.29492357,
       0.19500016, 0.43456287, 0.10864408, 0.49798632, 0.78611899,
       0.10191936, 0.62753931, 0.20052117, 0.53413779, 0.3061806 ,
       0.67006275, 0.68465604, 0.24046134, 0.61284925, 0.37403199,
       0.31923534, 0.42647917, 0.27050409, 0.20490174, 0.52194318,
       0.36557838, 0.10775394, 0.42471744, 0.43525905, 0.67460109,
       0.3187416 , 0.26548721, 0.55560946, 0.10617836, 0.54467405,
       0.50209689, 0.31524293, 0.25580121, 0.70246135, 0.31582732,
       0.27304337, 0.1092289 , 0.55102614, 0.10775394, 0.24399072,
       0.109888  , 0.56665871, 0.30806583, 0.57070944, 0.11168423,
       0.90561408, 0.13784907, 0.24440748, 0.11115204, 0.34226507,
       0.13865995, 0.50293514, 0.1170273 , 0.10775394, 0.51748395,
       0.27147953, 0.67099388, 0.43444524, 0.66696363, 0.91387818,
       0.16175873, 0.11678503, 0.42626876, 0.35074116, 0.83010958,
       0.36934508, 0.11333325, 0.51524976, 0.60678367, 0.24440748,
       0.60515844, 0.10721979, 0.35254412, 0.58510518, 0.1063997 ,
       0.11737468, 0.25909053, 0.17827107, 0.50200792, 0.1041903 ,
       0.10679652, 0.5914892 , 0.2880376 , 0.23086839, 0.18414332,
       0.14439256, 0.90211682, 0.68713756, 0.11795873, 0.27715165,
       0.12433748, 0.24036124, 0.44508181, 0.3305398 , 0.39122642,
       0.69568307, 0.56016756, 0.10140211, 0.28596719, 0.09546127,
       0.1153847 , 0.90733387, 0.26849371, 0.27715165, 0.56144073,
       0.30833369, 0.65235052, 0.3544602 , 0.10842825, 0.4347339 ,
       0.62196228, 0.70760594, 0.16125593, 0.49713596, 0.26500077,
       0.19719614, 0.48444001, 0.48447477, 0.1260207 , 0.19665657,
       0.44065422, 0.71145509, 0.78628546, 0.42912675, 0.48709133,
       0.52025522, 0.301473  , 0.7697372 , 0.46684484, 0.88939002,
       0.23586175, 0.77773052, 0.09852701, 0.08971092, 0.11917582,
       0.60167545, 0.17390614, 0.51461268, 0.49171835, 0.80444317,
       0.51413487, 0.42458045, 0.26957183, 0.53134458, 0.55086095,
       0.32857084, 0.35628022, 0.27794478, 0.43827186, 0.09799529,
       0.65364034, 0.30194244, 0.1137509 , 0.84859589, 0.1644333 ,
       0.14167731, 0.41972305, 0.16707021, 0.36218117, 0.16599562,
       0.66543623, 0.66572933, 0.28524626, 0.89698869, 0.10775394,
       0.36694429, 0.10530156, 0.32762418, 0.10721979, 0.41733261,
       0.360571  , 0.10721979, 0.31694893, 0.10096272, 0.52025522,
       0.66439505, 0.49287061, 0.11547684, 0.49747016, 0.28138404,
       0.43957658, 0.29481272, 0.51990091, 0.35999138, 0.46742346,
       0.81027974, 0.86172501, 0.30336734, 0.10617836, 0.11375704,
       0.60564357, 0.81677635, 0.66238169, 0.52674493, 0.48887116,
       0.47563711, 0.48604907, 0.46353601, 0.1063997 , 0.43239166,
       0.47305153, 0.51734572, 0.50939137, 0.78138625, 0.44484113,
       0.10879231, 0.43087012, 0.50050625, 0.49860713, 0.58479624,
       0.10617836, 0.15480331, 0.09804447, 0.63267583, 0.51442987,
       0.28271005, 0.1170273 , 0.91779558, 0.38528004, 0.52421524,
       0.88833312, 0.53608529, 0.13993758, 0.48208193, 0.51585815,
       0.26500077, 0.3769017 , 0.31694893, 0.37287694, 0.48175824,
       0.10682389, 0.1088652 , 0.27758763, 0.1260207 , 0.40989565,
       0.62349856, 0.70245645, 0.25082156, 0.72473289, 0.10762167,
       0.1081015 , 0.47924738, 0.63566892, 0.34732209, 0.52413487,
       0.45014798, 0.16449447, 0.13826647, 0.58969501, 0.31694893,
       0.74640248, 0.69601907, 0.61338413, 0.27524626, 0.64474314,
       0.5101991 , 0.62115651, 0.47281137, 0.30194244, 0.45107877,
       0.68546298, 0.7601317 , 0.23202448, 0.51890878, 0.7733761 ,
       0.11115204, 0.14118355, 0.5192753 , 0.6089001 , 0.48275786,
       0.52588726, 0.43466822, 0.75786438, 0.60167545, 0.64222127,
       0.88678022, 0.30587965, 0.2379691 , 0.39109151, 0.43162684,
       0.18599617, 0.26944224, 0.57691931, 0.14524567, 0.18888106,
       0.5594863 , 0.52940217, 0.10017084, 0.50544522, 0.11784274,
       0.65055746, 0.5192753 , 0.630597  , 0.43713925, 0.3735373 ,
       0.44070175, 0.28287627, 0.16887682, 0.22782148, 0.40993745,
       0.18636782, 0.86296937, 0.44432513, 0.50273471, 0.59184938,
       0.06577589, 0.40893092, 0.82075222, 0.10967709, 0.52250921,
       0.13463063, 0.60853896, 0.60051263, 0.88450071, 0.73221444,
       0.40214293, 0.51036355, 0.16287207, 0.11917582, 0.88150364,
       0.93364692, 0.52324828, 0.26577085, 0.23676629, 0.16436702,
       0.50273471, 0.50281826, 0.29694199, 0.58519129, 0.19502621,
       0.42205802, 0.430301  , 0.51122057, 0.11824914, 0.15706116,
       0.34957582, 0.39135628, 0.18278389, 0.64298129, 0.33062108,
       0.4740338 , 0.50682927, 0.50088026, 0.29547753, 0.4966124 ,
       0.4878266 , 0.13428867, 0.90846029, 0.23997536, 0.6496534 ,
       0.22666987, 0.13125538, 0.6783428 , 0.29913369, 0.58730662,
       0.31694893, 0.47544951, 0.64455204, 0.11151389, 0.47781348,
       0.40139027, 0.42765426, 0.57290911])

In [17]:
blending_pred = lr_pred*0.2  + gdbt_pred*0.5 + rf_pred*0.3
blending_pred

array([0.09490749, 0.38233157, 0.47784648, 0.54131671, 0.19975839,
       0.07432255, 0.37201764, 0.74319681, 0.82107227, 0.33496524,
       0.30935625, 0.60024134, 0.47675306, 0.07183907, 0.88576776,
       0.91408698, 0.62927785, 0.25130124, 0.44399883, 0.46108134,
       0.15104064, 0.44027421, 0.91225581, 0.31075437, 0.83317585,
       0.19003688, 0.67711016, 0.30229473, 0.73679837, 0.19564248,
       0.1551203 , 0.81414088, 0.69106275, 0.11071792, 0.34943688,
       0.20980622, 0.1791932 , 0.16260795, 0.27594741, 0.57275269,
       0.34132542, 0.73236448, 0.06782034, 0.86686482, 0.91591193,
       0.13887899, 0.16170302, 0.52688188, 0.50495588, 0.68599184,
       0.76408701, 0.17944896, 0.93054666, 0.78325164, 0.26821042,
       0.11173206, 0.27698267, 0.07868666, 0.43285664, 0.90914455,
       0.06882839, 0.78330063, 0.11417847, 0.74466453, 0.13857337,
       0.85297042, 0.8084923 , 0.16447718, 0.74271977, 0.2894359 ,
       0.26796444, 0.31125966, 0.23292752, 0.15772776, 0.71993151,
       0.50594362, 0.07889991, 0.37095464, 0.70360593, 0.71594028,
       0.29581447, 0.12652744, 0.63870637, 0.07060365, 0.55344935,
       0.32838164, 0.38034171, 0.173824  , 0.76355688, 0.27431987,
       0.18504234, 0.09381448, 0.60965429, 0.07889991, 0.32503298,
       0.11429486, 0.67849126, 0.63377407, 0.57617094, 0.07021979,
       0.93326381, 0.0980335 , 0.23291627, 0.10942902, 0.29530244,
       0.11021248, 0.5315275 , 0.09866171, 0.08269226, 0.55446832,
       0.17664879, 0.7408536 , 0.49890906, 0.6954563 , 0.92460137,
       0.11438483, 0.07824401, 0.42391923, 0.54236684, 0.87856241,
       0.3282755 , 0.07900581, 0.69152274, 0.70913895, 0.23291627,
       0.70049137, 0.11012205, 0.54287845, 0.66271532, 0.07306415,
       0.08788728, 0.17353958, 0.12125349, 0.30486186, 0.06397392,
       0.0809691 , 0.78395166, 0.21266303, 0.14779783, 0.10302769,
       0.09331523, 0.9440429 , 0.59912267, 0.11526924, 0.44101923,
       0.09677682, 0.22026189, 0.30217948, 0.49932576, 0.23016772,
       0.77649404, 0.62610731, 0.04183128, 0.19580055, 0.04820845,
       0.0655996 , 0.93939   , 0.20124104, 0.44101923, 0.70206514,
       0.2800156 , 0.60332845, 0.32929145, 0.1127253 , 0.62949899,
       0.69556214, 0.82740027, 0.06733557, 0.66535532, 0.16271953,
       0.09114233, 0.73815592, 0.36010798, 0.11210717, 0.15728268,
       0.41926625, 0.86955539, 0.84286496, 0.39763529, 0.38799406,
       0.60834235, 0.21702175, 0.89479515, 0.63433893, 0.92550453,
       0.17808966, 0.66731602, 0.06826791, 0.03979766, 0.10268106,
       0.61317654, 0.18842256, 0.38492813, 0.54997122, 0.87981425,
       0.46931758, 0.55771206, 0.20197568, 0.51213012, 0.5231031 ,
       0.27939403, 0.26413405, 0.16604069, 0.35287711, 0.08220946,
       0.73155984, 0.18204975, 0.08819059, 0.90596895, 0.1028152 ,
       0.12808633, 0.31002567, 0.09928537, 0.20153271, 0.12157555,
       0.8242668 , 0.77187257, 0.1943121 , 0.95188063, 0.07889991,
       0.50504805, 0.07405689, 0.21248309, 0.11118518, 0.27602822,
       0.31658272, 0.10819378, 0.30041001, 0.06147777, 0.55963307,
       0.78616923, 0.63049768, 0.0618581 , 0.5552895 , 0.20052813,
       0.39711634, 0.19701554, 0.67193745, 0.29885102, 0.49915484,
       0.87957698, 0.88875989, 0.29528259, 0.07060108, 0.05179632,
       0.5582824 , 0.8729871 , 0.68324779, 0.6666349 , 0.28653742,
       0.49901147, 0.36798127, 0.45463533, 0.0721429 , 0.38105942,
       0.43150206, 0.53628953, 0.43323044, 0.8433491 , 0.38780794,
       0.06876939, 0.60641645, 0.68497952, 0.56463245, 0.67922173,
       0.07060365, 0.09892315, 0.06056118, 0.48508424, 0.46979315,
       0.26903362, 0.09866171, 0.93957415, 0.3465705 , 0.58715988,
       0.9265438 , 0.53423591, 0.08191655, 0.67671165, 0.39436387,
       0.16139475, 0.40187766, 0.30041001, 0.30135207, 0.49761272,
       0.05232407, 0.06058522, 0.20081249, 0.11210717, 0.23692773,
       0.66655224, 0.41287125, 0.2724392 , 0.76141545, 0.08627709,
       0.08096057, 0.55280357, 0.6895986 , 0.29982957, 0.53077917,
       0.30972147, 0.13699474, 0.06143036, 0.61366034, 0.30041001,
       0.8649059 , 0.73993318, 0.6927556 , 0.18528391, 0.45192735,
       0.47100292, 0.76076779, 0.37757017, 0.16446102, 0.36770591,
       0.80751567, 0.77165737, 0.15439153, 0.59310757, 0.8633552 ,
       0.10942902, 0.15875501, 0.50227061, 0.75165312, 0.6420303 ,
       0.59445161, 0.399397  , 0.85535995, 0.62452427, 0.70107269,
       0.91021777, 0.25048716, 0.1717198 , 0.49506769, 0.39301099,
       0.19787583, 0.31887099, 0.51727583, 0.10787784, 0.14698998,
       0.76583518, 0.43262846, 0.04209482, 0.52342245, 0.06185684,
       0.72224907, 0.50227061, 0.46501054, 0.65867457, 0.47385343,
       0.46493745, 0.18513093, 0.09845235, 0.14112234, 0.3665212 ,
       0.13499932, 0.9333113 , 0.38282223, 0.52688188, 0.60685233,
       0.02821297, 0.4104567 , 0.89892539, 0.14341579, 0.67917368,
       0.06254425, 0.63967233, 0.62241075, 0.93030348, 0.8688685 ,
       0.46743427, 0.71809969, 0.08202044, 0.10120945, 0.92360306,
       0.94991515, 0.3605544 , 0.1676135 , 0.13696932, 0.14621106,
       0.52688188, 0.57316375, 0.20797016, 0.55062589, 0.24702463,
       0.3843108 , 0.60119045, 0.47201412, 0.09433711, 0.0794587 ,
       0.40659837, 0.31322095, 0.10388542, 0.74407703, 0.17239074,
       0.47001686, 0.42619434, 0.6510303 , 0.18900023, 0.36243734,
       0.63062707, 0.07960181, 0.94837306, 0.19374115, 0.62871758,
       0.33152694, 0.08945446, 0.83665736, 0.26726287, 0.75501041,
       0.30041001, 0.6371229 , 0.57216667, 0.07521232, 0.51581827,
       0.2227171 , 0.28937147, 0.62770606])